# Generated by Django 5.2.14 on 2026-05-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "related_entity_type",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("auction", "Auction"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("related_entity_id", models.BigIntegerField(db_index=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("refund", "Refund"),
                            ("confiscation", "Confiscation"),
                            ("commission", "Commission"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="JOD", max_length=8)),
                ("provider", models.CharField(blank=True, max_length=64)),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("method", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("requires_action", "Requires Action"),
                            ("authorized", "Authorized"),
                            ("succeeded", "Succeeded"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("disputed", "Disputed"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response_json", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "indexes": [
                    models.Index(
                        fields=["related_entity_type", "related_entity_id"],
                        name="payment_tra_related_aeccca_idx",
                    )
                ],
            },
        ),
    ]
