# Generated by Django 5.2.14 on 2026-05-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "increment_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "bid_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("quick_increment", "Quick Increment"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("outbid", "Outbid"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="accepted",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_highest_at_time", models.BooleanField(default=False)),
                (
                    "suppress_publication",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Accepted for bidder only: hidden from public bid list and does not advance auction price.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bids",
                        to="subscriptions.auctionsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "bids",
            },
        ),
        migrations.CreateModel(
            name="AuctionPriceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("bid", "Bid"),
                            ("rollback", "Rollback"),
                            ("manual_adjustment", "Manual Adjustment"),
                            ("close", "Close"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_snapshots",
                        to="auctions.auction",
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_snapshots",
                        to="bidding.bid",
                    ),
                ),
            ],
            options={
                "db_table": "auction_price_snapshots",
            },
        ),
        migrations.CreateModel(
            name="BidIdempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_idempotency_keys",
                        to="auctions.auction",
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="bidding.bid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid_idempotency_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bid_idempotency",
            },
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-created_at", "-id"], name="bids_auction_bf90c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auctionpricesnapshot",
            index=models.Index(
                fields=["auction", "-created_at"], name="auction_pri_auction_e3831d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bididempotency",
            constraint=models.UniqueConstraint(
                fields=("auction", "user", "key"),
                name="uniq_bid_idempotency_auction_user_key",
            ),
        ),
    ]
