# Generated by Django 5.2.14 on 2026-05-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        ("bidding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="winner_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_auctions",
                to="bidding.bid",
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="winner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auctions_won",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionmedia",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_items",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionreviewchecklist",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_checklist_items",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionreviewchecklist",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auction_checklist_checks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionreviewlog",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_logs",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionreviewlog",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auction_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionsharelog",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_logs",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionsharelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auction_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionwatchlist",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_entries",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionwatchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "ends_at"], name="auctions_status_0da26f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionwatchlist",
            constraint=models.UniqueConstraint(
                fields=("auction", "user"), name="uniq_watchlist_auction_user"
            ),
        ),
    ]
