# Generated by Django 5.2.14 on 2026-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_auctionreviewchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='duration_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
