# Generated by Django 5.2.14 on 2026-05-23 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("refunded", "Refunded"),
                            ("disqualified", "Disqualified"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=32,
                    ),
                ),
                (
                    "subscription_fee",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("confiscated", "Confiscated"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="auctions.auction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auction_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_method", models.CharField(blank=True, max_length=64)),
                ("payment_status", models.CharField(max_length=32)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("raw_gateway_response_json", models.JSONField(blank=True, null=True)),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_payments",
                        to="payments.paymenttransaction",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.auctionsubscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_payments",
            },
        ),
        migrations.AddIndex(
            model_name="auctionsubscription",
            index=models.Index(
                fields=["auction", "status"], name="auction_sub_auction_d35935_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionsubscription",
            constraint=models.UniqueConstraint(
                fields=("auction", "user"), name="uniq_subscription_auction_user"
            ),
        ),
    ]
