# Generated by Django 5.2.14 on 2026-06-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionsubscription',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='auctionsubscription',
            name='insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='auctionsubscription',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
