# Generated by Django 5.2.14 on 2026-05-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "cities",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128)),
                ("code", models.CharField(blank=True, max_length=3, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "countries",
                "db_table": "countries",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255)),
                ("category_type", models.CharField(blank=True, max_length=64)),
                ("requires_review", models.BooleanField(default=True)),
                ("requires_transfer_process", models.BooleanField(default=False)),
                ("requires_inspection", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "product_categories",
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=128)),
                ("name_en", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="catalog.city",
                    ),
                ),
            ],
            options={
                "db_table": "areas",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="catalog.country",
            ),
        ),
        migrations.CreateModel(
            name="ProductSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_images_count", models.PositiveSmallIntegerField(default=1)),
                ("max_images_count", models.PositiveSmallIntegerField(default=10)),
                ("video_allowed", models.BooleanField(default=False)),
                (
                    "max_video_duration_sec",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("attachments_allowed", models.BooleanField(default=False)),
                ("allowed_extensions_json", models.JSONField(blank=True, default=list)),
                ("location_link_enabled", models.BooleanField(default=False)),
                (
                    "min_start_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "min_bid_increment",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                ("reserve_price_required", models.BooleanField(default=False)),
                ("inspection_required", models.BooleanField(default=False)),
                ("blur_option_enabled", models.BooleanField(default=False)),
                (
                    "review_checklist_schema_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "subscription_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("delivery_period_days", models.PositiveSmallIntegerField(default=7)),
                ("auction_extension_enabled", models.BooleanField(default=False)),
                ("extension_minutes", models.PositiveSmallIntegerField(default=5)),
                (
                    "extension_trigger_seconds",
                    models.PositiveSmallIntegerField(default=30),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="catalog.productcategory",
                    ),
                ),
            ],
            options={
                "db_table": "product_settings",
            },
        ),
    ]
