# Generated by Django 5.2.14 on 2026-05-29 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_productsettings_review_checklist_schema_json_and_more'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='fees_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='configuration.feesconfiguration'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='review_checklist_items',
            field=models.ManyToManyField(blank=True, related_name='categories', through='configuration.ProductCategoryChecklist', to='configuration.reviewchecklistitem'),
        ),
    ]
